### ISSUE TITLE
Great solution - using aggressors to have right RMSE values !

### ISSUE THREAD

**Issue by dharani-aws** [saimoom026/Springboard#1]
Hi Saimoon
Thanks a ton for your detailed code to showcase how we can use external aggressors + fbprophet to fine tune a normal univariate series into a kind of multivariate one . The RMSE values have come down to 3.8 from 5.0 when I used a known external aggressor in my model of target Y .Thanks a lot for your valuable codebase all fbprophet enthusiasts !
Cheers
Dharani

**Comment by dharani-aws** [comment]
Closing the comment with thanks note

**Comment by saimoom026** [comment]
I am glad to know the fbprophet code benefited your work. Lets catch up more!
